# Generated by Django 4.1.3 on 2023-03-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0002_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('ism', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
