# Generated by Django 4.1.3 on 2023-03-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
